/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BeianFooter: typeof import('./components/BeianFooter.vue')['default']
    ColumnDragHandle: typeof import('./components/ColumnDragHandle.vue')['default']
    ColumnFilterPopover: typeof import('./components/ColumnFilterPopover.vue')['default']
    ColumnVisibilityPopover: typeof import('./components/ColumnVisibilityPopover.vue')['default']
    CosUploader: typeof import('./components/CosUploader/index.vue')['default']
    EChart: typeof import('./components/EChart.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ListShell: typeof import('./components/ListShell.vue')['default']
    NotificationBanner: typeof import('./components/NotificationBanner.vue')['default']
    PagedTable: typeof import('./components/PagedTable.vue')['default']
    PdfViewer: typeof import('./components/PdfViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepViewer: typeof import('./components/cad-viewer/StepViewer.vue')['default']
    StepViewerProgress: typeof import('./components/cad-viewer/StepViewerProgress.vue')['default']
    StepViewerToolbar: typeof import('./components/cad-viewer/StepViewerToolbar.vue')['default']
    UploadStatusCellView: typeof import('./components/UploadStatusCellView.vue')['default']
  }
}
